sudo: required
language: rust
cache: cargo

# feature mocking is needed to execute tests with mocking
matrix:
  include:
    - rust: nightly
      env: FEATURES=mocking
      before_script:
        - rustup component add clippy-preview || return 0
        - rustup component add rustfmt-preview || return 0
      before_cache:
        - cargo install cargo-update || echo "cargo-update already installed"
        - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin || echo "cargo-tarpaulin already installed"
        - cargo install-update cargo-update
        - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install-update cargo-tarpaulin
      after_success:
        - RUST_BACKTRACE=full cargo tarpaulin --out Xml
        - bash <(curl -s https://codecov.io/bash)
    - rust: beta
    - rust: stable
    - rust: 1.37.0

    - language: nix
      name: nix build on nixpkgs-unstable
      before_script:
        - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
        - nix-channel --update
        - nix eval nixpkgs.rustc.version
      script:
        # use nix-build because travis bulid get killed after 10 minutes without output
        # - nix build --verbose
        - nix-build --argstr cargoSha256 0l6x59bzzilc78gsi5rlgq9zjvp8qjphfsds776ljzmkbdq8q4iz
    - language: nix
      name: nix build on nixos-19.09
      before_script:
        - nix-channel --add https://nixos.org/channels/nixos-19.09 nixpkgs
        - nix-channel --update
        - nix eval nixpkgs.rustc.version
      script:
        # use nix-build because travis bulid get killed after 10 minutes without output
        # - nix build --verbose
        - nix-build

script:
  - |
    if [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]] && $(rustup component list | grep installed | grep rustfmt-preview > /dev/null); then
      cargo fmt -- --verbose --check
    fi
  - cargo check --verbose --features "$FEATURES"
  - cargo build --verbose --features "$FEATURES"
  - |
    if [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]] && $(rustup component list | grep installed | grep clippy-preview > /dev/null); then
      cargo clippy --verbose --features "$FEATURES"
    fi
  - cargo test --verbose --features "$FEATURES"

addons:
  apt:
    packages:
      - libdbus-1-dev
      - libgdk-pixbuf2.0-dev
      - libglib2.0-dev
      - libnotify-dev
      - libssl-dev # for tarpaulin
